### ISSUE TITLE
Image Tag

### ISSUE THREAD

**Issue by jeremymeyers** [xiffy/lfm#1]
Would it be possible to add the track/album cover image as an image tag within the rss?

**Comment by xiffy** [comment]
i see what i can do, seems i'll be coding on lfm this weekend :-)

**Comment by xiffy** [comment]
It's live, if we get something else as a default image, the track/album/artist image is included as an enclosure

**Comment by chaos-baum** [comment]
While working on the code i stumbled upon the image tags. While testing my code I also noticed that the image was always the same even for artists/tracks which definitly have images on them. So I found this: https://support.last.fm/t/broken-artist-images-in-user-gettopartists-and-user-gettoptracks/1558

While there is no real issue with the images, the code itself will never be usefull because last.fm shutdown the corresponding feature.
